name: Build and Upload Artifacts

on:
  workflow_dispatch:
  push:
    branches:
      - test-ci
      - master
  pull_request:
    branches:
      - deploy

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check files changed
        uses: ./.github/actions/check-changed-files
        id: check-files-changed
    outputs:
      should_build: ${{ steps.check-files-changed.outputs.is_angular_changed == 'true' }}

  fail-early:
    needs: check-files
    if: ${{ needs.check-files.outputs.should_build == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fail and notice
        uses: actions/github-script@v5
        with:
          script: |
            core.setFailed('Fail-safe. OK to ignore. Moving to Netlify workflow');

  build:
    needs: check-files
    if: ${{ needs.check-files.outputs.should_build == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-deps
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup NodeJS
        uses: actions/setup-node@v2

      - name: Install dependencies
        if: ${{ steps.cached-deps.outputs.cache-hit != 'true' }}
        run: npm install -g pnpm && pnpm install

      - name: Download Nx Cache
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v2
        with:
          name: post-nx-cache
          workflow: build-and-upload-artifacts.yml
          path: ./node_modules/.cache/nx

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - name: Build projects
        run: |
          if [ "${{ env.NX_BASE == '' || env.NX_BASE == null || env.NX_HEAD == '' || env.NX_HEAD == null }}" = "true" ];
          then
            yarn build:web:prod
          else
            yarn build:web:affected
          fi

      - name: Upload Nx Cache
        uses: actions/upload-artifact@v2
        with:
          name: post-nx-cache
          path: ./node_modules/.cache/nx

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: post-build-artifacts
          path: |
            ./dist/apps/web
            ./dist/libs/web
